### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-acurite-temperature#1]
Aug  3 19:45:10 raj homebridge[16383]: Fri, 03 Aug 2018 23:45:10 GMT acurite Message {"time" : "2018-08-03 19:45:10", "model" : "Efergy e2 CT", "id" : 9729, "current" : inf, "interval" : 18, "battery" : "LOW", "learn" : "YES"}
Aug  3 19:45:10 raj homebridge[16383]: Disconnected Apple TV's
Aug  3 19:45:10 raj homebridge[16383]: undefined:1
Aug  3 19:45:10 raj homebridge[16383]: {"time" : "2018-08-03 19:45:10", "model" : "Efergy e2 CT", "id" : 9729, "current" : inf, "interval" : 18, "battery" : "LOW", "learn" : "YES"}
Aug  3 19:45:10 raj homebridge[16383]: ^
Aug  3 19:45:10 raj homebridge[16383]: SyntaxError: Unexpected token i in JSON at position 84
Aug  3 19:45:10 raj homebridge[16383]: at JSON.parse (<anonymous>:null:null)
Aug  3 19:45:10 raj homebridge[16383]: at AcuritePlugin.<anonymous> (/home/sgracey/node_modules/homebridge-acurite-temperature/sensor.js:60:25)
Aug  3 19:45:10 raj homebridge[16383]: at emitOne (events.js:96:13)
Aug  3 19:45:10 raj homebridge[16383]: at Interface.emit (events.js:191:7)
Aug  3 19:45:10 raj homebridge[16383]: at Interface._onLine (readline.js:241:10)
Aug  3 19:45:10 raj homebridge[16383]: at Interface._normalWrite (readline.js:384:12)
Aug  3 19:45:10 raj homebridge[16383]: at Socket.ondata (readline.js:101:10)

**Comment by NorthernMan54** [comment]
Fixed in v0.0.6
